name: Automated E2E Testing
on: 
  - pull_request
  - workflow_dispatch

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main
        
      - name: Start server
        run: npm start & wait-on http://localhost:5500

      - name: run cypress tests with electron
        uses: cypress-io/github-action@v4
        with:
          browser: electron
