name: Automated E2E Testing
on:
  - pull_request
  - workflow_dispatch

env:
  email: ${{secrets.TEST_EMAIL}}
  password: ${{secrets.TEST_PASSWORD}}

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Install dependencies
        run: npm i

      - name: Build Sass
        run: npm run build

      - name: run cypress tests with electron
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          browser: electron
